spring.application.name=leaderboardproject

spring.datasource.url = jdbc:postgresql://localhost:5432/leaderboarddb
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=your_jwt_secret_key
server.port=8080