spring.application.name=leaderboardproject

spring.datasource.url = jdbc:postgresql://localhost:5432/leaderboarddb
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=ThisIsASecretKeyForJwtTokenGeneration2024MakeItLong
jwt.expiration=3600000
server.port=8080
leaderboard.refresh.cron=0 0 0 * * *
#leaderboard.refresh.cron=0 * * * * *
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email