spring.application.name=leaderboardproject
#FRONTEND_URL=http://localhost:5173
FRONTEND_URL=${FRONTEND_URL}
spring.datasource.url = ${DATASOURCE_URL}
spring.datasource.username = ${DATASOURCE_USER}
spring.datasource.password = ${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=ThisIsASecretKeyForJwtTokenGeneration2024MakeItLong
jwt.expiration=86400000
server.port=8080
#leaderboard.refresh.cron=0 0 0 * * *
leaderboard.refresh.cron=0 * * * * *
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinry.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB